{
  /*total data 40 with id */
}
const data = [
  {
    id: 1,
    image: product1,
    heading: "Syltherine",
    subheading: "Stylish Cafe Chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "-30%",
    discountFlag: true,
  },
  {
    id: 2,
    image: product2,
    heading: "Leviosa",
    subheading: "Stylish cafe chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.300.000",
    discount: "Rp.500.000",
  },
  {
    id: 3,
    image: product3,
    heading: "Lolito",
    subheading: "Luxury big sofa",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 4,
    image: product4,
    heading: "Respira",
    subheading: "Bar table and stool",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 5,
    image: product5,
    heading: "Grifo",
    subheading: "Night lamp",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.800.000",
  },
  {
    id: 6,
    image: product6,
    heading: "Muggo",
    subheading: "lgall mug",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 7,
    image: product7,
    heading: "Pingky",
    subheading: "Cute bed set",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 8,
    image: product8,
    heading: "Potty",
    subheading: "Minimalist flower pot",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 9,
    image: product8,
    heading: "Potty",
    subheading: "Minimalist flower pot",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 10,
    image: product6,
    heading: "Muggo",
    subheading: "Small mug",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 11,
    image: product4,
    heading: "Respira",
    subheading: "Bar table and stool",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 12,
    image: product2,
    heading: "Leviosa",
    subheading: "Stylish cafe chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.300.000",
    discount: "Rp.500.000",
  },
  {
    id: 13,
    image: product1,
    heading: "Syltherine",
    subheading: "Stylish Cafe Chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "-30%",
    discountFlag: true,
  },
  {
    id: 14,
    image: product5,
    heading: "Grifo",
    subheading: "Night lamp",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.800.000",
  },
  {
    id: 15,
    image: product3,
    heading: "Lolito",
    subheading: "Luxury big sofa",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 16,
    image: product7,
    heading: "Pingky",
    subheading: "Cute bed set",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 17,
    image: product8,
    heading: "Potty",
    subheading: "Minimalist flower pot",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 18,
    image: product6,
    heading: "Muggo",
    subheading: "Small mug",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 19,
    image: product4,
    heading: "Respira",
    subheading: "Bar table and stool",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 20,
    image: product2,
    heading: "Leviosa",
    subheading: "Stylish cafe chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.300.000",
    discount: "Rp.500.000",
  },
  {
    id: 21,
    image: product1,
    heading: "Syltherine",
    subheading: "Stylish Cafe Chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "-30%",
    discountFlag: true,
  },
  {
    id: 22,
    image: product5,
    heading: "Grifo",
    subheading: "Night lamp",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.800.000",
  },
  {
    id: 23,
    image: product3,
    heading: "Lolito",
    subheading: "Luxury big sofa",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 24,
    image: product7,
    heading: "Pingky",
    subheading: "Cute bed set",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 25,
    image: product1,
    heading: "Syltherine",
    subheading: "Stylish Cafe Chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "-30%",
    discountFlag: true,
  },
  {
    id: 26,
    image: product2,
    heading: "Leviosa",
    subheading: "Stylish cafe chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.300.000",
    discount: "Rp.500.000",
  },
  {
    id: 27,
    image: product3,
    heading: "Lolito",
    subheading: "Luxury big sofa",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 28,
    image: product4,
    heading: "Respira",
    subheading: "Bar table and stool",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 29,
    image: product5,
    heading: "Grifo",
    subheading: "Night lamp",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.800.000",
  },
  {
    id: 30,
    image: product6,
    heading: "Muggo",
    subheading: "Small mug",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 31,
    image: product7,
    heading: "Pingky",
    subheading: "Cute bed set",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 32,
    image: product8,
    heading: "Potty",
    subheading: "Minimalist flower pot",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 33,
    image: product1,
    heading: "Syltherine",
    subheading: "Stylish Cafe Chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "-30%",
    discountFlag: true,
  },
  {
    id: 34,
    image: product2,
    heading: "Leviosa",
    subheading: "Stylish cafe chair",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.300.000",
    discount: "Rp.500.000",
  },
  {
    id: 35,
    image: product3,
    heading: "Lolito",
    subheading: "Luxury big sofa",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 36,
    image: product4,
    heading: "Respira",
    subheading: "Bar table and stool",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 37,
    image: product5,
    heading: "Grifo",
    subheading: "Night lamp",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.800.000",
  },
  {
    id: 38,
    image: product6,
    heading: "Muggo",
    subheading: "Small mug",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
  {
    id: 39,
    image: product7,
    heading: "Pingky",
    subheading: "Cute bed set",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "700.000",
    discount: "Rp.900.000",
    tag: "-50%",
    discountFlag: true,
  },
  {
    id: 40,
    image: product8,
    heading: "Potty",
    subheading: "Minimalist flower pot",
    para: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: "Rp.500.000",
    discount: "Rp.900.000",
    tag: "New",
    discountFlag: false,
  },
];
